# Manually audited.
class("java.lang.RuntimeException",
  honorary("org.joe_e.Powerless"),
  static(constructor("RuntimeException()"),
    constructor("RuntimeException(String)"),
    constructor("RuntimeException(String, Throwable)"),
    constructor(suppress, "RuntimeException(Throwable)", comment("calls toString on cause to generate message"))))
